POST http://localhost:8088/kafka/?message=write%201st%20message
###
POST http://localhost:8088/kafka/?message=write%202nd%20message
###
POST http://localhost:8088/kafka/?message=write%203rd%20message
###
POST http://localhost:8088/kafka/?message=write%204th%20message
###
POST http://localhost:8088/kafka/?message=write%205th%20message
###
POST http://localhost:8088/kafka/?message=write%206th%20message
###
###
POST http://localhost:8088/kafka/sendItem
Content-Type: application/json

{
  "type": "palrago",
  "key": "20230303160400",
  "action": "CREATE",
  "message": "장터거래 등록"
}

###
POST http://localhost:8088/kafka/sendItem
Content-Type: application/json

{
  "type": "mobilepop",
  "key": "20230303161600",
  "action": "UPDATE",
  "message": "환불거래 발생"
}